import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { cloudflare } from "@cloudflare/vite-plugin";
import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

/*
 * Plain `bun run dev` points development at the production D1 database — reads and writes both.
 * `bun run dev:local` is the explicit isolated Miniflare escape hatch. Remote development requires
 * `wrangler login` and expects the remote schema to be current (`bun run db:migrate:remote`).
 */
const remoteDatabase = Boolean(process.env.BUTTERCREAM_REMOTE_DB);

/*
 * The Cloudflare plugin only honours a binding's `remote` flag when it reads it from the config
 * file — a `config` customizer that adds it after parsing never reaches the remote-session
 * setup, and the flag is silently ignored. So remote dev writes a derived, gitignored config next
 * to the real one (same directory, so relative paths keep resolving) and points the plugin at it.
 */
function writeRemoteWranglerConfig(): string {
  const source = fileURLToPath(new URL("./wrangler.jsonc", import.meta.url));
  const raw = readFileSync(source, "utf8");
  /* Line comments only, and only when preceded by line start or whitespace, so "https://" in
     string values survives. wrangler.jsonc has no block comments to worry about. */
  const config = JSON.parse(raw.replace(/(^|\s)\/\/.*$/gm, "$1"));
  config.d1_databases = config.d1_databases?.map((database: Record<string, unknown>) => ({
    ...database,
    remote: true,
  }));
  const target = fileURLToPath(new URL("./wrangler.remote.jsonc", import.meta.url));
  writeFileSync(
    target,
    `// GENERATED by dev from wrangler.jsonc — do not edit or commit.\n${JSON.stringify(config, null, 2)}\n`,
  );
  return target;
}

export default defineConfig({
  optimizeDeps: {
    include: ["@base-ui/react/alert-dialog", "@base-ui/react/dialog"],
  },
  plugins: [
    cloudflare({
      inspectorPort: false,
      viteEnvironment: { name: "ssr" },
      ...(remoteDatabase ? { configPath: writeRemoteWranglerConfig() } : {}),
    }),
    tailwindcss(),
    tanstackStart(),
    react(),
  ],
  ssr: {
    optimizeDeps: {
      include: ["@base-ui/react/alert-dialog", "@base-ui/react/dialog"],
    },
  },
});
