import { createDefaultDesignSystem, themeLayerCss } from "@buttercream/theme-core";

/*
 * Prints `src/theme-defaults.css`: the default preset's token blocks, as CSS.
 *
 * The default preset is not special. It is a design system document like any other, and the
 * stylesheet this package ships is its export — printed by the same `themeLayerCss` a consumer's
 * own `global.css` comes out of. Before this existed the values were typed into `theme.css` by
 * hand, which meant the document and the stylesheet could disagree, and once did.
 *
 * Run by this package's `build` script. `theme-defaults.test.ts` fails if the committed file is
 * not what this prints.
 */

export const GENERATED_HEADER = `/*
 * Generated by scripts/generate-theme-defaults.ts — do not edit.
 *
 * The default design system document, printed as CSS. Change a value in
 * @buttercream/theme-core's \`defaults.ts\` and re-run \`bun run build\` in this package.
 */`;

export function renderThemeDefaults(): string {
  return `${GENERATED_HEADER}\n\n${themeLayerCss(createDefaultDesignSystem().theme)}\n`;
}

if (import.meta.main) {
  const target = new URL("../src/theme-defaults.css", import.meta.url);
  await Bun.write(target, renderThemeDefaults());
  console.log(`Wrote ${target.pathname}`);
}
