import type { DesignSystem } from "@buttercream/theme-core";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  Add01Icon as bulkRoundedAdd,
  ArrowUp01Icon as bulkRoundedArrowUp,
  Attachment01Icon as bulkRoundedAttach,
  CheckmarkCircle02Icon as bulkRoundedCheck,
  ArrowDown01Icon as bulkRoundedChevronDown,
  Cancel01Icon as bulkRoundedClose,
  Copy01Icon as bulkRoundedCopy,
  Delete02Icon as bulkRoundedDelete,
  Globe02Icon as bulkRoundedGlobe,
  Mail01Icon as bulkRoundedMail,
  MoreHorizontalIcon as bulkRoundedMore,
  RefreshIcon as bulkRoundedRefresh,
  Search01Icon as bulkRoundedSearch,
  Settings02Icon as bulkRoundedSettings,
  ThumbsDownIcon as bulkRoundedThumbDown,
  ThumbsUpIcon as bulkRoundedThumbUp,
  Upload01Icon as bulkRoundedUpload,
  UserGroupIcon as bulkRoundedUsers,
  Alert02Icon as bulkRoundedWarning,
} from "@hugeicons-pro/core-bulk-rounded";
import {
  Add01Icon as duotoneRoundedAdd,
  ArrowUp01Icon as duotoneRoundedArrowUp,
  Attachment01Icon as duotoneRoundedAttach,
  CheckmarkCircle02Icon as duotoneRoundedCheck,
  ArrowDown01Icon as duotoneRoundedChevronDown,
  Cancel01Icon as duotoneRoundedClose,
  Copy01Icon as duotoneRoundedCopy,
  Delete02Icon as duotoneRoundedDelete,
  Globe02Icon as duotoneRoundedGlobe,
  Mail01Icon as duotoneRoundedMail,
  MoreHorizontalIcon as duotoneRoundedMore,
  RefreshIcon as duotoneRoundedRefresh,
  Search01Icon as duotoneRoundedSearch,
  Settings02Icon as duotoneRoundedSettings,
  ThumbsDownIcon as duotoneRoundedThumbDown,
  ThumbsUpIcon as duotoneRoundedThumbUp,
  Upload01Icon as duotoneRoundedUpload,
  UserGroupIcon as duotoneRoundedUsers,
  Alert02Icon as duotoneRoundedWarning,
} from "@hugeicons-pro/core-duotone-rounded";
import {
  Add01Icon as duotoneStandardAdd,
  ArrowUp01Icon as duotoneStandardArrowUp,
  Attachment01Icon as duotoneStandardAttach,
  CheckmarkCircle02Icon as duotoneStandardCheck,
  ArrowDown01Icon as duotoneStandardChevronDown,
  Cancel01Icon as duotoneStandardClose,
  Copy01Icon as duotoneStandardCopy,
  Delete02Icon as duotoneStandardDelete,
  Globe02Icon as duotoneStandardGlobe,
  Mail01Icon as duotoneStandardMail,
  MoreHorizontalIcon as duotoneStandardMore,
  RefreshIcon as duotoneStandardRefresh,
  Search01Icon as duotoneStandardSearch,
  Settings02Icon as duotoneStandardSettings,
  ThumbsDownIcon as duotoneStandardThumbDown,
  ThumbsUpIcon as duotoneStandardThumbUp,
  Upload01Icon as duotoneStandardUpload,
  UserGroupIcon as duotoneStandardUsers,
  Alert02Icon as duotoneStandardWarning,
} from "@hugeicons-pro/core-duotone-standard";
import {
  Add01Icon as solidRoundedAdd,
  ArrowUp01Icon as solidRoundedArrowUp,
  Attachment01Icon as solidRoundedAttach,
  CheckmarkCircle02Icon as solidRoundedCheck,
  ArrowDown01Icon as solidRoundedChevronDown,
  Cancel01Icon as solidRoundedClose,
  Copy01Icon as solidRoundedCopy,
  Delete02Icon as solidRoundedDelete,
  Globe02Icon as solidRoundedGlobe,
  Mail01Icon as solidRoundedMail,
  MoreHorizontalIcon as solidRoundedMore,
  RefreshIcon as solidRoundedRefresh,
  Search01Icon as solidRoundedSearch,
  Settings02Icon as solidRoundedSettings,
  ThumbsDownIcon as solidRoundedThumbDown,
  ThumbsUpIcon as solidRoundedThumbUp,
  Upload01Icon as solidRoundedUpload,
  UserGroupIcon as solidRoundedUsers,
  Alert02Icon as solidRoundedWarning,
} from "@hugeicons-pro/core-solid-rounded";
import {
  Add01Icon as solidSharpAdd,
  ArrowUp01Icon as solidSharpArrowUp,
  Attachment01Icon as solidSharpAttach,
  CheckmarkCircle02Icon as solidSharpCheck,
  ArrowDown01Icon as solidSharpChevronDown,
  Cancel01Icon as solidSharpClose,
  Copy01Icon as solidSharpCopy,
  Delete02Icon as solidSharpDelete,
  Globe02Icon as solidSharpGlobe,
  Mail01Icon as solidSharpMail,
  MoreHorizontalIcon as solidSharpMore,
  RefreshIcon as solidSharpRefresh,
  Search01Icon as solidSharpSearch,
  Settings02Icon as solidSharpSettings,
  ThumbsDownIcon as solidSharpThumbDown,
  ThumbsUpIcon as solidSharpThumbUp,
  Upload01Icon as solidSharpUpload,
  UserGroupIcon as solidSharpUsers,
  Alert02Icon as solidSharpWarning,
} from "@hugeicons-pro/core-solid-sharp";
import {
  Add01Icon as solidStandardAdd,
  ArrowUp01Icon as solidStandardArrowUp,
  Attachment01Icon as solidStandardAttach,
  CheckmarkCircle02Icon as solidStandardCheck,
  ArrowDown01Icon as solidStandardChevronDown,
  Cancel01Icon as solidStandardClose,
  Copy01Icon as solidStandardCopy,
  Delete02Icon as solidStandardDelete,
  Globe02Icon as solidStandardGlobe,
  Mail01Icon as solidStandardMail,
  MoreHorizontalIcon as solidStandardMore,
  RefreshIcon as solidStandardRefresh,
  Search01Icon as solidStandardSearch,
  Settings02Icon as solidStandardSettings,
  ThumbsDownIcon as solidStandardThumbDown,
  ThumbsUpIcon as solidStandardThumbUp,
  Upload01Icon as solidStandardUpload,
  UserGroupIcon as solidStandardUsers,
  Alert02Icon as solidStandardWarning,
} from "@hugeicons-pro/core-solid-standard";
import {
  Add01Icon as strokeRoundedAdd,
  ArrowUp01Icon as strokeRoundedArrowUp,
  Attachment01Icon as strokeRoundedAttach,
  CheckmarkCircle02Icon as strokeRoundedCheck,
  ArrowDown01Icon as strokeRoundedChevronDown,
  Cancel01Icon as strokeRoundedClose,
  Copy01Icon as strokeRoundedCopy,
  Delete02Icon as strokeRoundedDelete,
  Globe02Icon as strokeRoundedGlobe,
  Mail01Icon as strokeRoundedMail,
  MoreHorizontalIcon as strokeRoundedMore,
  RefreshIcon as strokeRoundedRefresh,
  Search01Icon as strokeRoundedSearch,
  Settings02Icon as strokeRoundedSettings,
  ThumbsDownIcon as strokeRoundedThumbDown,
  ThumbsUpIcon as strokeRoundedThumbUp,
  Upload01Icon as strokeRoundedUpload,
  UserGroupIcon as strokeRoundedUsers,
  Alert02Icon as strokeRoundedWarning,
} from "@hugeicons-pro/core-stroke-rounded";
import {
  Add01Icon as strokeSharpAdd,
  ArrowUp01Icon as strokeSharpArrowUp,
  Attachment01Icon as strokeSharpAttach,
  CheckmarkCircle02Icon as strokeSharpCheck,
  ArrowDown01Icon as strokeSharpChevronDown,
  Cancel01Icon as strokeSharpClose,
  Copy01Icon as strokeSharpCopy,
  Delete02Icon as strokeSharpDelete,
  Globe02Icon as strokeSharpGlobe,
  Mail01Icon as strokeSharpMail,
  MoreHorizontalIcon as strokeSharpMore,
  RefreshIcon as strokeSharpRefresh,
  Search01Icon as strokeSharpSearch,
  Settings02Icon as strokeSharpSettings,
  ThumbsDownIcon as strokeSharpThumbDown,
  ThumbsUpIcon as strokeSharpThumbUp,
  Upload01Icon as strokeSharpUpload,
  UserGroupIcon as strokeSharpUsers,
  Alert02Icon as strokeSharpWarning,
} from "@hugeicons-pro/core-stroke-sharp";
import {
  Add01Icon as strokeStandardAdd,
  ArrowUp01Icon as strokeStandardArrowUp,
  Attachment01Icon as strokeStandardAttach,
  CheckmarkCircle02Icon as strokeStandardCheck,
  ArrowDown01Icon as strokeStandardChevronDown,
  Cancel01Icon as strokeStandardClose,
  Copy01Icon as strokeStandardCopy,
  Delete02Icon as strokeStandardDelete,
  Globe02Icon as strokeStandardGlobe,
  Mail01Icon as strokeStandardMail,
  MoreHorizontalIcon as strokeStandardMore,
  RefreshIcon as strokeStandardRefresh,
  Search01Icon as strokeStandardSearch,
  Settings02Icon as strokeStandardSettings,
  ThumbsDownIcon as strokeStandardThumbDown,
  ThumbsUpIcon as strokeStandardThumbUp,
  Upload01Icon as strokeStandardUpload,
  UserGroupIcon as strokeStandardUsers,
  Alert02Icon as strokeStandardWarning,
} from "@hugeicons-pro/core-stroke-standard";
import {
  Add01Icon as twotoneRoundedAdd,
  ArrowUp01Icon as twotoneRoundedArrowUp,
  Attachment01Icon as twotoneRoundedAttach,
  CheckmarkCircle02Icon as twotoneRoundedCheck,
  ArrowDown01Icon as twotoneRoundedChevronDown,
  Cancel01Icon as twotoneRoundedClose,
  Copy01Icon as twotoneRoundedCopy,
  Delete02Icon as twotoneRoundedDelete,
  Globe02Icon as twotoneRoundedGlobe,
  Mail01Icon as twotoneRoundedMail,
  MoreHorizontalIcon as twotoneRoundedMore,
  RefreshIcon as twotoneRoundedRefresh,
  Search01Icon as twotoneRoundedSearch,
  Settings02Icon as twotoneRoundedSettings,
  ThumbsDownIcon as twotoneRoundedThumbDown,
  ThumbsUpIcon as twotoneRoundedThumbUp,
  Upload01Icon as twotoneRoundedUpload,
  UserGroupIcon as twotoneRoundedUsers,
  Alert02Icon as twotoneRoundedWarning,
} from "@hugeicons-pro/core-twotone-rounded";
import {
  ArrowUp,
  ChevronDown,
  CircleCheck,
  Copy,
  Ellipsis,
  Globe,
  type LucideIcon,
  Mail,
  Paperclip,
  Plus,
  RefreshCw,
  Search,
  Settings,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TriangleAlert,
  Upload,
  Users,
  X,
} from "lucide-react";
import { type ComponentProps, createElement, type ReactElement } from "react";

type IconSettings = DesignSystem["icons"];
type HugeiconsSettings = Extract<IconSettings, { family: "hugeicons" }>;
type IconData = ComponentProps<typeof HugeiconsIcon>["icon"];

export type PreviewIconName =
  | "add"
  | "arrowUp"
  | "attach"
  | "check"
  | "chevronDown"
  | "close"
  | "copy"
  | "delete"
  | "globe"
  | "mail"
  | "more"
  | "refresh"
  | "search"
  | "settings"
  | "thumbDown"
  | "thumbUp"
  | "upload"
  | "users"
  | "warning";

export type PreviewIconElements = Record<PreviewIconName, ReactElement>;

const previewIconNames: PreviewIconName[] = [
  "add",
  "arrowUp",
  "attach",
  "check",
  "chevronDown",
  "close",
  "copy",
  "delete",
  "globe",
  "mail",
  "more",
  "refresh",
  "search",
  "settings",
  "thumbDown",
  "thumbUp",
  "upload",
  "users",
  "warning",
];

const lucideIcons = {
  add: Plus,
  arrowUp: ArrowUp,
  attach: Paperclip,
  check: CircleCheck,
  chevronDown: ChevronDown,
  close: X,
  copy: Copy,
  delete: Trash2,
  globe: Globe,
  mail: Mail,
  more: Ellipsis,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  thumbDown: ThumbsDown,
  thumbUp: ThumbsUp,
  upload: Upload,
  users: Users,
  warning: TriangleAlert,
} satisfies Record<PreviewIconName, LucideIcon>;

// Keep package specifiers static so Vite can tree-shake each treatment to this preview vocabulary.
const hugeiconsByTreatment = {
  "bulk-rounded": {
    add: bulkRoundedAdd,
    arrowUp: bulkRoundedArrowUp,
    attach: bulkRoundedAttach,
    check: bulkRoundedCheck,
    chevronDown: bulkRoundedChevronDown,
    close: bulkRoundedClose,
    copy: bulkRoundedCopy,
    delete: bulkRoundedDelete,
    globe: bulkRoundedGlobe,
    mail: bulkRoundedMail,
    more: bulkRoundedMore,
    refresh: bulkRoundedRefresh,
    search: bulkRoundedSearch,
    settings: bulkRoundedSettings,
    thumbDown: bulkRoundedThumbDown,
    thumbUp: bulkRoundedThumbUp,
    upload: bulkRoundedUpload,
    users: bulkRoundedUsers,
    warning: bulkRoundedWarning,
  },
  "duotone-rounded": {
    add: duotoneRoundedAdd,
    arrowUp: duotoneRoundedArrowUp,
    attach: duotoneRoundedAttach,
    check: duotoneRoundedCheck,
    chevronDown: duotoneRoundedChevronDown,
    close: duotoneRoundedClose,
    copy: duotoneRoundedCopy,
    delete: duotoneRoundedDelete,
    globe: duotoneRoundedGlobe,
    mail: duotoneRoundedMail,
    more: duotoneRoundedMore,
    refresh: duotoneRoundedRefresh,
    search: duotoneRoundedSearch,
    settings: duotoneRoundedSettings,
    thumbDown: duotoneRoundedThumbDown,
    thumbUp: duotoneRoundedThumbUp,
    upload: duotoneRoundedUpload,
    users: duotoneRoundedUsers,
    warning: duotoneRoundedWarning,
  },
  "duotone-standard": {
    add: duotoneStandardAdd,
    arrowUp: duotoneStandardArrowUp,
    attach: duotoneStandardAttach,
    check: duotoneStandardCheck,
    chevronDown: duotoneStandardChevronDown,
    close: duotoneStandardClose,
    copy: duotoneStandardCopy,
    delete: duotoneStandardDelete,
    globe: duotoneStandardGlobe,
    mail: duotoneStandardMail,
    more: duotoneStandardMore,
    refresh: duotoneStandardRefresh,
    search: duotoneStandardSearch,
    settings: duotoneStandardSettings,
    thumbDown: duotoneStandardThumbDown,
    thumbUp: duotoneStandardThumbUp,
    upload: duotoneStandardUpload,
    users: duotoneStandardUsers,
    warning: duotoneStandardWarning,
  },
  "solid-rounded": {
    add: solidRoundedAdd,
    arrowUp: solidRoundedArrowUp,
    attach: solidRoundedAttach,
    check: solidRoundedCheck,
    chevronDown: solidRoundedChevronDown,
    close: solidRoundedClose,
    copy: solidRoundedCopy,
    delete: solidRoundedDelete,
    globe: solidRoundedGlobe,
    mail: solidRoundedMail,
    more: solidRoundedMore,
    refresh: solidRoundedRefresh,
    search: solidRoundedSearch,
    settings: solidRoundedSettings,
    thumbDown: solidRoundedThumbDown,
    thumbUp: solidRoundedThumbUp,
    upload: solidRoundedUpload,
    users: solidRoundedUsers,
    warning: solidRoundedWarning,
  },
  "solid-sharp": {
    add: solidSharpAdd,
    arrowUp: solidSharpArrowUp,
    attach: solidSharpAttach,
    check: solidSharpCheck,
    chevronDown: solidSharpChevronDown,
    close: solidSharpClose,
    copy: solidSharpCopy,
    delete: solidSharpDelete,
    globe: solidSharpGlobe,
    mail: solidSharpMail,
    more: solidSharpMore,
    refresh: solidSharpRefresh,
    search: solidSharpSearch,
    settings: solidSharpSettings,
    thumbDown: solidSharpThumbDown,
    thumbUp: solidSharpThumbUp,
    upload: solidSharpUpload,
    users: solidSharpUsers,
    warning: solidSharpWarning,
  },
  "solid-standard": {
    add: solidStandardAdd,
    arrowUp: solidStandardArrowUp,
    attach: solidStandardAttach,
    check: solidStandardCheck,
    chevronDown: solidStandardChevronDown,
    close: solidStandardClose,
    copy: solidStandardCopy,
    delete: solidStandardDelete,
    globe: solidStandardGlobe,
    mail: solidStandardMail,
    more: solidStandardMore,
    refresh: solidStandardRefresh,
    search: solidStandardSearch,
    settings: solidStandardSettings,
    thumbDown: solidStandardThumbDown,
    thumbUp: solidStandardThumbUp,
    upload: solidStandardUpload,
    users: solidStandardUsers,
    warning: solidStandardWarning,
  },
  "stroke-rounded": {
    add: strokeRoundedAdd,
    arrowUp: strokeRoundedArrowUp,
    attach: strokeRoundedAttach,
    check: strokeRoundedCheck,
    chevronDown: strokeRoundedChevronDown,
    close: strokeRoundedClose,
    copy: strokeRoundedCopy,
    delete: strokeRoundedDelete,
    globe: strokeRoundedGlobe,
    mail: strokeRoundedMail,
    more: strokeRoundedMore,
    refresh: strokeRoundedRefresh,
    search: strokeRoundedSearch,
    settings: strokeRoundedSettings,
    thumbDown: strokeRoundedThumbDown,
    thumbUp: strokeRoundedThumbUp,
    upload: strokeRoundedUpload,
    users: strokeRoundedUsers,
    warning: strokeRoundedWarning,
  },
  "stroke-sharp": {
    add: strokeSharpAdd,
    arrowUp: strokeSharpArrowUp,
    attach: strokeSharpAttach,
    check: strokeSharpCheck,
    chevronDown: strokeSharpChevronDown,
    close: strokeSharpClose,
    copy: strokeSharpCopy,
    delete: strokeSharpDelete,
    globe: strokeSharpGlobe,
    mail: strokeSharpMail,
    more: strokeSharpMore,
    refresh: strokeSharpRefresh,
    search: strokeSharpSearch,
    settings: strokeSharpSettings,
    thumbDown: strokeSharpThumbDown,
    thumbUp: strokeSharpThumbUp,
    upload: strokeSharpUpload,
    users: strokeSharpUsers,
    warning: strokeSharpWarning,
  },
  "stroke-standard": {
    add: strokeStandardAdd,
    arrowUp: strokeStandardArrowUp,
    attach: strokeStandardAttach,
    check: strokeStandardCheck,
    chevronDown: strokeStandardChevronDown,
    close: strokeStandardClose,
    copy: strokeStandardCopy,
    delete: strokeStandardDelete,
    globe: strokeStandardGlobe,
    mail: strokeStandardMail,
    more: strokeStandardMore,
    refresh: strokeStandardRefresh,
    search: strokeStandardSearch,
    settings: strokeStandardSettings,
    thumbDown: strokeStandardThumbDown,
    thumbUp: strokeStandardThumbUp,
    upload: strokeStandardUpload,
    users: strokeStandardUsers,
    warning: strokeStandardWarning,
  },
  "twotone-rounded": {
    add: twotoneRoundedAdd,
    arrowUp: twotoneRoundedArrowUp,
    attach: twotoneRoundedAttach,
    check: twotoneRoundedCheck,
    chevronDown: twotoneRoundedChevronDown,
    close: twotoneRoundedClose,
    copy: twotoneRoundedCopy,
    delete: twotoneRoundedDelete,
    globe: twotoneRoundedGlobe,
    mail: twotoneRoundedMail,
    more: twotoneRoundedMore,
    refresh: twotoneRoundedRefresh,
    search: twotoneRoundedSearch,
    settings: twotoneRoundedSettings,
    thumbDown: twotoneRoundedThumbDown,
    thumbUp: twotoneRoundedThumbUp,
    upload: twotoneRoundedUpload,
    users: twotoneRoundedUsers,
    warning: twotoneRoundedWarning,
  },
} satisfies Record<HugeiconsSettings["treatment"], Record<PreviewIconName, IconData>>;

export function createPreviewIconElements(settings: IconSettings): PreviewIconElements {
  return Object.fromEntries(
    previewIconNames.map((name) => [name, previewIconElement(name, settings)]),
  ) as PreviewIconElements;
}

function previewIconElement(name: PreviewIconName, settings: IconSettings): ReactElement {
  if (settings.family === "lucide") {
    return createElement(lucideIcons[name], {
      "aria-hidden": true,
      className: "preview-icon",
      size: settings.size,
      strokeWidth: settings.strokeWidth,
    });
  }

  return createElement(HugeiconsIcon, {
    "aria-hidden": true,
    className: "preview-icon",
    icon: hugeiconsByTreatment[settings.treatment][name],
    size: settings.size,
    strokeWidth: settings.strokeWidth,
  });
}
