import type { DesignSystem } from "@buttercream/theme-core";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  Add01Icon as bulkRoundedAdd,
  Archive02Icon as bulkRoundedArchive,
  ArrowUp01Icon as bulkRoundedArrowUp,
  Attachment01Icon as bulkRoundedAttach,
  BookOpen01Icon as bulkRoundedBook,
  BotIcon as bulkRoundedBot,
  PackageIcon as bulkRoundedBox,
  Calendar03Icon as bulkRoundedCalendar,
  CreditCardIcon as bulkRoundedCard,
  ShoppingBag01Icon as bulkRoundedCart,
  ChartColumnIcon as bulkRoundedChart,
  CheckmarkCircle02Icon as bulkRoundedCheck,
  Tick02Icon as bulkRoundedCheckmark,
  ArrowDown01Icon as bulkRoundedChevronDown,
  Cancel01Icon as bulkRoundedClose,
  SourceCodeIcon as bulkRoundedCode,
  Copy01Icon as bulkRoundedCopy,
  Scissor01Icon as bulkRoundedCut,
  Delete02Icon as bulkRoundedDelete,
  PencilEdit02Icon as bulkRoundedEdit,
  LinkSquare02Icon as bulkRoundedExternalLink,
  File01Icon as bulkRoundedFile,
  FolderAddIcon as bulkRoundedFolderAdd,
  FolderOpenIcon as bulkRoundedFolderOpen,
  Globe02Icon as bulkRoundedGlobe,
  GridViewIcon as bulkRoundedGrid,
  HelpCircleIcon as bulkRoundedHelp,
  Home01Icon as bulkRoundedHome,
  LibraryIcon as bulkRoundedLibrary,
  ListViewIcon as bulkRoundedList,
  SquareLock02Icon as bulkRoundedLock,
  Logout03Icon as bulkRoundedLogout,
  Mail01Icon as bulkRoundedMail,
  BubbleChatIcon as bulkRoundedMessage,
  MoreHorizontalIcon as bulkRoundedMore,
  MoreVerticalIcon as bulkRoundedMoreVertical,
  Notification03Icon as bulkRoundedNotification,
  NotificationOff01Icon as bulkRoundedNotificationOff,
  PaintBoardIcon as bulkRoundedPalette,
  ClipboardPasteIcon as bulkRoundedPaste,
  SmartPhone01Icon as bulkRoundedPhone,
  Invoice01Icon as bulkRoundedReceipt,
  RefreshIcon as bulkRoundedRefresh,
  ReturnRequestIcon as bulkRoundedRefund,
  Rocket01Icon as bulkRoundedRocket,
  ScanIcon as bulkRoundedScan,
  Search01Icon as bulkRoundedSearch,
  Settings02Icon as bulkRoundedSettings,
  SidebarLeftIcon as bulkRoundedSidebar,
  SparklesIcon as bulkRoundedSparkle,
  StarIcon as bulkRoundedStar,
  Tag01Icon as bulkRoundedTag,
  Target02Icon as bulkRoundedTarget,
  Task01Icon as bulkRoundedTask,
  ComputerTerminal01Icon as bulkRoundedTerminal,
  ThumbsDownIcon as bulkRoundedThumbDown,
  ThumbsUpIcon as bulkRoundedThumbUp,
  UnfoldMoreIcon as bulkRoundedUnfold,
  Upload01Icon as bulkRoundedUpload,
  UserIcon as bulkRoundedUser,
  UserGroupIcon as bulkRoundedUsers,
  Alert02Icon as bulkRoundedWarning,
  HierarchyCircle01Icon as bulkRoundedWorkflow,
} from "@hugeicons-pro/core-bulk-rounded";
import {
  Add01Icon as duotoneRoundedAdd,
  Archive02Icon as duotoneRoundedArchive,
  ArrowUp01Icon as duotoneRoundedArrowUp,
  Attachment01Icon as duotoneRoundedAttach,
  BookOpen01Icon as duotoneRoundedBook,
  BotIcon as duotoneRoundedBot,
  PackageIcon as duotoneRoundedBox,
  Calendar03Icon as duotoneRoundedCalendar,
  CreditCardIcon as duotoneRoundedCard,
  ShoppingBag01Icon as duotoneRoundedCart,
  ChartColumnIcon as duotoneRoundedChart,
  CheckmarkCircle02Icon as duotoneRoundedCheck,
  Tick02Icon as duotoneRoundedCheckmark,
  ArrowDown01Icon as duotoneRoundedChevronDown,
  Cancel01Icon as duotoneRoundedClose,
  SourceCodeIcon as duotoneRoundedCode,
  Copy01Icon as duotoneRoundedCopy,
  Scissor01Icon as duotoneRoundedCut,
  Delete02Icon as duotoneRoundedDelete,
  PencilEdit02Icon as duotoneRoundedEdit,
  LinkSquare02Icon as duotoneRoundedExternalLink,
  File01Icon as duotoneRoundedFile,
  FolderAddIcon as duotoneRoundedFolderAdd,
  FolderOpenIcon as duotoneRoundedFolderOpen,
  Globe02Icon as duotoneRoundedGlobe,
  GridViewIcon as duotoneRoundedGrid,
  HelpCircleIcon as duotoneRoundedHelp,
  Home01Icon as duotoneRoundedHome,
  LibraryIcon as duotoneRoundedLibrary,
  ListViewIcon as duotoneRoundedList,
  SquareLock02Icon as duotoneRoundedLock,
  Logout03Icon as duotoneRoundedLogout,
  Mail01Icon as duotoneRoundedMail,
  BubbleChatIcon as duotoneRoundedMessage,
  MoreHorizontalIcon as duotoneRoundedMore,
  MoreVerticalIcon as duotoneRoundedMoreVertical,
  Notification03Icon as duotoneRoundedNotification,
  NotificationOff01Icon as duotoneRoundedNotificationOff,
  PaintBoardIcon as duotoneRoundedPalette,
  ClipboardPasteIcon as duotoneRoundedPaste,
  SmartPhone01Icon as duotoneRoundedPhone,
  Invoice01Icon as duotoneRoundedReceipt,
  RefreshIcon as duotoneRoundedRefresh,
  ReturnRequestIcon as duotoneRoundedRefund,
  Rocket01Icon as duotoneRoundedRocket,
  ScanIcon as duotoneRoundedScan,
  Search01Icon as duotoneRoundedSearch,
  Settings02Icon as duotoneRoundedSettings,
  SidebarLeftIcon as duotoneRoundedSidebar,
  SparklesIcon as duotoneRoundedSparkle,
  StarIcon as duotoneRoundedStar,
  Tag01Icon as duotoneRoundedTag,
  Target02Icon as duotoneRoundedTarget,
  Task01Icon as duotoneRoundedTask,
  ComputerTerminal01Icon as duotoneRoundedTerminal,
  ThumbsDownIcon as duotoneRoundedThumbDown,
  ThumbsUpIcon as duotoneRoundedThumbUp,
  UnfoldMoreIcon as duotoneRoundedUnfold,
  Upload01Icon as duotoneRoundedUpload,
  UserIcon as duotoneRoundedUser,
  UserGroupIcon as duotoneRoundedUsers,
  Alert02Icon as duotoneRoundedWarning,
  HierarchyCircle01Icon as duotoneRoundedWorkflow,
} from "@hugeicons-pro/core-duotone-rounded";
import {
  Add01Icon as duotoneStandardAdd,
  Archive02Icon as duotoneStandardArchive,
  ArrowUp01Icon as duotoneStandardArrowUp,
  Attachment01Icon as duotoneStandardAttach,
  BookOpen01Icon as duotoneStandardBook,
  BotIcon as duotoneStandardBot,
  PackageIcon as duotoneStandardBox,
  Calendar03Icon as duotoneStandardCalendar,
  CreditCardIcon as duotoneStandardCard,
  ShoppingBag01Icon as duotoneStandardCart,
  ChartColumnIcon as duotoneStandardChart,
  CheckmarkCircle02Icon as duotoneStandardCheck,
  Tick02Icon as duotoneStandardCheckmark,
  ArrowDown01Icon as duotoneStandardChevronDown,
  Cancel01Icon as duotoneStandardClose,
  SourceCodeIcon as duotoneStandardCode,
  Copy01Icon as duotoneStandardCopy,
  Scissor01Icon as duotoneStandardCut,
  Delete02Icon as duotoneStandardDelete,
  PencilEdit02Icon as duotoneStandardEdit,
  LinkSquare02Icon as duotoneStandardExternalLink,
  File01Icon as duotoneStandardFile,
  FolderAddIcon as duotoneStandardFolderAdd,
  FolderOpenIcon as duotoneStandardFolderOpen,
  Globe02Icon as duotoneStandardGlobe,
  GridViewIcon as duotoneStandardGrid,
  HelpCircleIcon as duotoneStandardHelp,
  Home01Icon as duotoneStandardHome,
  LibraryIcon as duotoneStandardLibrary,
  ListViewIcon as duotoneStandardList,
  SquareLock02Icon as duotoneStandardLock,
  Logout03Icon as duotoneStandardLogout,
  Mail01Icon as duotoneStandardMail,
  BubbleChatIcon as duotoneStandardMessage,
  MoreHorizontalIcon as duotoneStandardMore,
  MoreVerticalIcon as duotoneStandardMoreVertical,
  Notification03Icon as duotoneStandardNotification,
  NotificationOff01Icon as duotoneStandardNotificationOff,
  PaintBoardIcon as duotoneStandardPalette,
  ClipboardPasteIcon as duotoneStandardPaste,
  SmartPhone01Icon as duotoneStandardPhone,
  Invoice01Icon as duotoneStandardReceipt,
  RefreshIcon as duotoneStandardRefresh,
  ReturnRequestIcon as duotoneStandardRefund,
  Rocket01Icon as duotoneStandardRocket,
  ScanIcon as duotoneStandardScan,
  Search01Icon as duotoneStandardSearch,
  Settings02Icon as duotoneStandardSettings,
  SidebarLeftIcon as duotoneStandardSidebar,
  SparklesIcon as duotoneStandardSparkle,
  StarIcon as duotoneStandardStar,
  Tag01Icon as duotoneStandardTag,
  Target02Icon as duotoneStandardTarget,
  Task01Icon as duotoneStandardTask,
  ComputerTerminal01Icon as duotoneStandardTerminal,
  ThumbsDownIcon as duotoneStandardThumbDown,
  ThumbsUpIcon as duotoneStandardThumbUp,
  UnfoldMoreIcon as duotoneStandardUnfold,
  Upload01Icon as duotoneStandardUpload,
  UserIcon as duotoneStandardUser,
  UserGroupIcon as duotoneStandardUsers,
  Alert02Icon as duotoneStandardWarning,
  HierarchyCircle01Icon as duotoneStandardWorkflow,
} from "@hugeicons-pro/core-duotone-standard";
import {
  Add01Icon as solidRoundedAdd,
  Archive02Icon as solidRoundedArchive,
  ArrowUp01Icon as solidRoundedArrowUp,
  Attachment01Icon as solidRoundedAttach,
  BookOpen01Icon as solidRoundedBook,
  BotIcon as solidRoundedBot,
  PackageIcon as solidRoundedBox,
  Calendar03Icon as solidRoundedCalendar,
  CreditCardIcon as solidRoundedCard,
  ShoppingBag01Icon as solidRoundedCart,
  ChartColumnIcon as solidRoundedChart,
  CheckmarkCircle02Icon as solidRoundedCheck,
  Tick02Icon as solidRoundedCheckmark,
  ArrowDown01Icon as solidRoundedChevronDown,
  Cancel01Icon as solidRoundedClose,
  SourceCodeIcon as solidRoundedCode,
  Copy01Icon as solidRoundedCopy,
  Scissor01Icon as solidRoundedCut,
  Delete02Icon as solidRoundedDelete,
  PencilEdit02Icon as solidRoundedEdit,
  LinkSquare02Icon as solidRoundedExternalLink,
  File01Icon as solidRoundedFile,
  FolderAddIcon as solidRoundedFolderAdd,
  FolderOpenIcon as solidRoundedFolderOpen,
  Globe02Icon as solidRoundedGlobe,
  GridViewIcon as solidRoundedGrid,
  HelpCircleIcon as solidRoundedHelp,
  Home01Icon as solidRoundedHome,
  LibraryIcon as solidRoundedLibrary,
  ListViewIcon as solidRoundedList,
  SquareLock02Icon as solidRoundedLock,
  Logout03Icon as solidRoundedLogout,
  Mail01Icon as solidRoundedMail,
  BubbleChatIcon as solidRoundedMessage,
  MoreHorizontalIcon as solidRoundedMore,
  MoreVerticalIcon as solidRoundedMoreVertical,
  Notification03Icon as solidRoundedNotification,
  NotificationOff01Icon as solidRoundedNotificationOff,
  PaintBoardIcon as solidRoundedPalette,
  ClipboardPasteIcon as solidRoundedPaste,
  SmartPhone01Icon as solidRoundedPhone,
  Invoice01Icon as solidRoundedReceipt,
  RefreshIcon as solidRoundedRefresh,
  ReturnRequestIcon as solidRoundedRefund,
  Rocket01Icon as solidRoundedRocket,
  ScanIcon as solidRoundedScan,
  Search01Icon as solidRoundedSearch,
  Settings02Icon as solidRoundedSettings,
  SidebarLeftIcon as solidRoundedSidebar,
  SparklesIcon as solidRoundedSparkle,
  StarIcon as solidRoundedStar,
  Tag01Icon as solidRoundedTag,
  Target02Icon as solidRoundedTarget,
  Task01Icon as solidRoundedTask,
  ComputerTerminal01Icon as solidRoundedTerminal,
  ThumbsDownIcon as solidRoundedThumbDown,
  ThumbsUpIcon as solidRoundedThumbUp,
  UnfoldMoreIcon as solidRoundedUnfold,
  Upload01Icon as solidRoundedUpload,
  UserIcon as solidRoundedUser,
  UserGroupIcon as solidRoundedUsers,
  Alert02Icon as solidRoundedWarning,
  HierarchyCircle01Icon as solidRoundedWorkflow,
} from "@hugeicons-pro/core-solid-rounded";
import {
  Add01Icon as solidSharpAdd,
  Archive02Icon as solidSharpArchive,
  ArrowUp01Icon as solidSharpArrowUp,
  Attachment01Icon as solidSharpAttach,
  BookOpen01Icon as solidSharpBook,
  BotIcon as solidSharpBot,
  PackageIcon as solidSharpBox,
  Calendar03Icon as solidSharpCalendar,
  CreditCardIcon as solidSharpCard,
  ShoppingBag01Icon as solidSharpCart,
  ChartColumnIcon as solidSharpChart,
  CheckmarkCircle02Icon as solidSharpCheck,
  Tick02Icon as solidSharpCheckmark,
  ArrowDown01Icon as solidSharpChevronDown,
  Cancel01Icon as solidSharpClose,
  SourceCodeIcon as solidSharpCode,
  Copy01Icon as solidSharpCopy,
  Scissor01Icon as solidSharpCut,
  Delete02Icon as solidSharpDelete,
  PencilEdit02Icon as solidSharpEdit,
  LinkSquare02Icon as solidSharpExternalLink,
  File01Icon as solidSharpFile,
  FolderAddIcon as solidSharpFolderAdd,
  FolderOpenIcon as solidSharpFolderOpen,
  Globe02Icon as solidSharpGlobe,
  GridViewIcon as solidSharpGrid,
  HelpCircleIcon as solidSharpHelp,
  Home01Icon as solidSharpHome,
  LibraryIcon as solidSharpLibrary,
  ListViewIcon as solidSharpList,
  SquareLock02Icon as solidSharpLock,
  Logout03Icon as solidSharpLogout,
  Mail01Icon as solidSharpMail,
  BubbleChatIcon as solidSharpMessage,
  MoreHorizontalIcon as solidSharpMore,
  MoreVerticalIcon as solidSharpMoreVertical,
  Notification03Icon as solidSharpNotification,
  NotificationOff01Icon as solidSharpNotificationOff,
  PaintBoardIcon as solidSharpPalette,
  ClipboardPasteIcon as solidSharpPaste,
  SmartPhone01Icon as solidSharpPhone,
  Invoice01Icon as solidSharpReceipt,
  RefreshIcon as solidSharpRefresh,
  ReturnRequestIcon as solidSharpRefund,
  Rocket01Icon as solidSharpRocket,
  ScanIcon as solidSharpScan,
  Search01Icon as solidSharpSearch,
  Settings02Icon as solidSharpSettings,
  SidebarLeftIcon as solidSharpSidebar,
  SparklesIcon as solidSharpSparkle,
  StarIcon as solidSharpStar,
  Tag01Icon as solidSharpTag,
  Target02Icon as solidSharpTarget,
  Task01Icon as solidSharpTask,
  ComputerTerminal01Icon as solidSharpTerminal,
  ThumbsDownIcon as solidSharpThumbDown,
  ThumbsUpIcon as solidSharpThumbUp,
  UnfoldMoreIcon as solidSharpUnfold,
  Upload01Icon as solidSharpUpload,
  UserIcon as solidSharpUser,
  UserGroupIcon as solidSharpUsers,
  Alert02Icon as solidSharpWarning,
  HierarchyCircle01Icon as solidSharpWorkflow,
} from "@hugeicons-pro/core-solid-sharp";
import {
  Add01Icon as solidStandardAdd,
  Archive02Icon as solidStandardArchive,
  ArrowUp01Icon as solidStandardArrowUp,
  Attachment01Icon as solidStandardAttach,
  BookOpen01Icon as solidStandardBook,
  BotIcon as solidStandardBot,
  PackageIcon as solidStandardBox,
  Calendar03Icon as solidStandardCalendar,
  CreditCardIcon as solidStandardCard,
  ShoppingBag01Icon as solidStandardCart,
  ChartColumnIcon as solidStandardChart,
  CheckmarkCircle02Icon as solidStandardCheck,
  Tick02Icon as solidStandardCheckmark,
  ArrowDown01Icon as solidStandardChevronDown,
  Cancel01Icon as solidStandardClose,
  SourceCodeIcon as solidStandardCode,
  Copy01Icon as solidStandardCopy,
  Scissor01Icon as solidStandardCut,
  Delete02Icon as solidStandardDelete,
  PencilEdit02Icon as solidStandardEdit,
  LinkSquare02Icon as solidStandardExternalLink,
  File01Icon as solidStandardFile,
  FolderAddIcon as solidStandardFolderAdd,
  FolderOpenIcon as solidStandardFolderOpen,
  Globe02Icon as solidStandardGlobe,
  GridViewIcon as solidStandardGrid,
  HelpCircleIcon as solidStandardHelp,
  Home01Icon as solidStandardHome,
  LibraryIcon as solidStandardLibrary,
  ListViewIcon as solidStandardList,
  SquareLock02Icon as solidStandardLock,
  Logout03Icon as solidStandardLogout,
  Mail01Icon as solidStandardMail,
  BubbleChatIcon as solidStandardMessage,
  MoreHorizontalIcon as solidStandardMore,
  MoreVerticalIcon as solidStandardMoreVertical,
  Notification03Icon as solidStandardNotification,
  NotificationOff01Icon as solidStandardNotificationOff,
  PaintBoardIcon as solidStandardPalette,
  ClipboardPasteIcon as solidStandardPaste,
  SmartPhone01Icon as solidStandardPhone,
  Invoice01Icon as solidStandardReceipt,
  RefreshIcon as solidStandardRefresh,
  ReturnRequestIcon as solidStandardRefund,
  Rocket01Icon as solidStandardRocket,
  ScanIcon as solidStandardScan,
  Search01Icon as solidStandardSearch,
  Settings02Icon as solidStandardSettings,
  SidebarLeftIcon as solidStandardSidebar,
  SparklesIcon as solidStandardSparkle,
  StarIcon as solidStandardStar,
  Tag01Icon as solidStandardTag,
  Target02Icon as solidStandardTarget,
  Task01Icon as solidStandardTask,
  ComputerTerminal01Icon as solidStandardTerminal,
  ThumbsDownIcon as solidStandardThumbDown,
  ThumbsUpIcon as solidStandardThumbUp,
  UnfoldMoreIcon as solidStandardUnfold,
  Upload01Icon as solidStandardUpload,
  UserIcon as solidStandardUser,
  UserGroupIcon as solidStandardUsers,
  Alert02Icon as solidStandardWarning,
  HierarchyCircle01Icon as solidStandardWorkflow,
} from "@hugeicons-pro/core-solid-standard";
import {
  Add01Icon as strokeRoundedAdd,
  Archive02Icon as strokeRoundedArchive,
  ArrowUp01Icon as strokeRoundedArrowUp,
  Attachment01Icon as strokeRoundedAttach,
  BookOpen01Icon as strokeRoundedBook,
  BotIcon as strokeRoundedBot,
  PackageIcon as strokeRoundedBox,
  Calendar03Icon as strokeRoundedCalendar,
  CreditCardIcon as strokeRoundedCard,
  ShoppingBag01Icon as strokeRoundedCart,
  ChartColumnIcon as strokeRoundedChart,
  CheckmarkCircle02Icon as strokeRoundedCheck,
  Tick02Icon as strokeRoundedCheckmark,
  ArrowDown01Icon as strokeRoundedChevronDown,
  Cancel01Icon as strokeRoundedClose,
  SourceCodeIcon as strokeRoundedCode,
  Copy01Icon as strokeRoundedCopy,
  Scissor01Icon as strokeRoundedCut,
  Delete02Icon as strokeRoundedDelete,
  PencilEdit02Icon as strokeRoundedEdit,
  LinkSquare02Icon as strokeRoundedExternalLink,
  File01Icon as strokeRoundedFile,
  FolderAddIcon as strokeRoundedFolderAdd,
  FolderOpenIcon as strokeRoundedFolderOpen,
  Globe02Icon as strokeRoundedGlobe,
  GridViewIcon as strokeRoundedGrid,
  HelpCircleIcon as strokeRoundedHelp,
  Home01Icon as strokeRoundedHome,
  LibraryIcon as strokeRoundedLibrary,
  ListViewIcon as strokeRoundedList,
  SquareLock02Icon as strokeRoundedLock,
  Logout03Icon as strokeRoundedLogout,
  Mail01Icon as strokeRoundedMail,
  BubbleChatIcon as strokeRoundedMessage,
  MoreHorizontalIcon as strokeRoundedMore,
  MoreVerticalIcon as strokeRoundedMoreVertical,
  Notification03Icon as strokeRoundedNotification,
  NotificationOff01Icon as strokeRoundedNotificationOff,
  PaintBoardIcon as strokeRoundedPalette,
  ClipboardPasteIcon as strokeRoundedPaste,
  SmartPhone01Icon as strokeRoundedPhone,
  Invoice01Icon as strokeRoundedReceipt,
  RefreshIcon as strokeRoundedRefresh,
  ReturnRequestIcon as strokeRoundedRefund,
  Rocket01Icon as strokeRoundedRocket,
  ScanIcon as strokeRoundedScan,
  Search01Icon as strokeRoundedSearch,
  Settings02Icon as strokeRoundedSettings,
  SidebarLeftIcon as strokeRoundedSidebar,
  SparklesIcon as strokeRoundedSparkle,
  StarIcon as strokeRoundedStar,
  Tag01Icon as strokeRoundedTag,
  Target02Icon as strokeRoundedTarget,
  Task01Icon as strokeRoundedTask,
  ComputerTerminal01Icon as strokeRoundedTerminal,
  ThumbsDownIcon as strokeRoundedThumbDown,
  ThumbsUpIcon as strokeRoundedThumbUp,
  UnfoldMoreIcon as strokeRoundedUnfold,
  Upload01Icon as strokeRoundedUpload,
  UserIcon as strokeRoundedUser,
  UserGroupIcon as strokeRoundedUsers,
  Alert02Icon as strokeRoundedWarning,
  HierarchyCircle01Icon as strokeRoundedWorkflow,
} from "@hugeicons-pro/core-stroke-rounded";
import {
  Add01Icon as strokeSharpAdd,
  Archive02Icon as strokeSharpArchive,
  ArrowUp01Icon as strokeSharpArrowUp,
  Attachment01Icon as strokeSharpAttach,
  BookOpen01Icon as strokeSharpBook,
  BotIcon as strokeSharpBot,
  PackageIcon as strokeSharpBox,
  Calendar03Icon as strokeSharpCalendar,
  CreditCardIcon as strokeSharpCard,
  ShoppingBag01Icon as strokeSharpCart,
  ChartColumnIcon as strokeSharpChart,
  CheckmarkCircle02Icon as strokeSharpCheck,
  Tick02Icon as strokeSharpCheckmark,
  ArrowDown01Icon as strokeSharpChevronDown,
  Cancel01Icon as strokeSharpClose,
  SourceCodeIcon as strokeSharpCode,
  Copy01Icon as strokeSharpCopy,
  Scissor01Icon as strokeSharpCut,
  Delete02Icon as strokeSharpDelete,
  PencilEdit02Icon as strokeSharpEdit,
  LinkSquare02Icon as strokeSharpExternalLink,
  File01Icon as strokeSharpFile,
  FolderAddIcon as strokeSharpFolderAdd,
  FolderOpenIcon as strokeSharpFolderOpen,
  Globe02Icon as strokeSharpGlobe,
  GridViewIcon as strokeSharpGrid,
  HelpCircleIcon as strokeSharpHelp,
  Home01Icon as strokeSharpHome,
  LibraryIcon as strokeSharpLibrary,
  ListViewIcon as strokeSharpList,
  SquareLock02Icon as strokeSharpLock,
  Logout03Icon as strokeSharpLogout,
  Mail01Icon as strokeSharpMail,
  BubbleChatIcon as strokeSharpMessage,
  MoreHorizontalIcon as strokeSharpMore,
  MoreVerticalIcon as strokeSharpMoreVertical,
  Notification03Icon as strokeSharpNotification,
  NotificationOff01Icon as strokeSharpNotificationOff,
  PaintBoardIcon as strokeSharpPalette,
  ClipboardPasteIcon as strokeSharpPaste,
  SmartPhone01Icon as strokeSharpPhone,
  Invoice01Icon as strokeSharpReceipt,
  RefreshIcon as strokeSharpRefresh,
  ReturnRequestIcon as strokeSharpRefund,
  Rocket01Icon as strokeSharpRocket,
  ScanIcon as strokeSharpScan,
  Search01Icon as strokeSharpSearch,
  Settings02Icon as strokeSharpSettings,
  SidebarLeftIcon as strokeSharpSidebar,
  SparklesIcon as strokeSharpSparkle,
  StarIcon as strokeSharpStar,
  Tag01Icon as strokeSharpTag,
  Target02Icon as strokeSharpTarget,
  Task01Icon as strokeSharpTask,
  ComputerTerminal01Icon as strokeSharpTerminal,
  ThumbsDownIcon as strokeSharpThumbDown,
  ThumbsUpIcon as strokeSharpThumbUp,
  UnfoldMoreIcon as strokeSharpUnfold,
  Upload01Icon as strokeSharpUpload,
  UserIcon as strokeSharpUser,
  UserGroupIcon as strokeSharpUsers,
  Alert02Icon as strokeSharpWarning,
  HierarchyCircle01Icon as strokeSharpWorkflow,
} from "@hugeicons-pro/core-stroke-sharp";
import {
  Add01Icon as strokeStandardAdd,
  Archive02Icon as strokeStandardArchive,
  ArrowUp01Icon as strokeStandardArrowUp,
  Attachment01Icon as strokeStandardAttach,
  BookOpen01Icon as strokeStandardBook,
  BotIcon as strokeStandardBot,
  PackageIcon as strokeStandardBox,
  Calendar03Icon as strokeStandardCalendar,
  CreditCardIcon as strokeStandardCard,
  ShoppingBag01Icon as strokeStandardCart,
  ChartColumnIcon as strokeStandardChart,
  CheckmarkCircle02Icon as strokeStandardCheck,
  Tick02Icon as strokeStandardCheckmark,
  ArrowDown01Icon as strokeStandardChevronDown,
  Cancel01Icon as strokeStandardClose,
  SourceCodeIcon as strokeStandardCode,
  Copy01Icon as strokeStandardCopy,
  Scissor01Icon as strokeStandardCut,
  Delete02Icon as strokeStandardDelete,
  PencilEdit02Icon as strokeStandardEdit,
  LinkSquare02Icon as strokeStandardExternalLink,
  File01Icon as strokeStandardFile,
  FolderAddIcon as strokeStandardFolderAdd,
  FolderOpenIcon as strokeStandardFolderOpen,
  Globe02Icon as strokeStandardGlobe,
  GridViewIcon as strokeStandardGrid,
  HelpCircleIcon as strokeStandardHelp,
  Home01Icon as strokeStandardHome,
  LibraryIcon as strokeStandardLibrary,
  ListViewIcon as strokeStandardList,
  SquareLock02Icon as strokeStandardLock,
  Logout03Icon as strokeStandardLogout,
  Mail01Icon as strokeStandardMail,
  BubbleChatIcon as strokeStandardMessage,
  MoreHorizontalIcon as strokeStandardMore,
  MoreVerticalIcon as strokeStandardMoreVertical,
  Notification03Icon as strokeStandardNotification,
  NotificationOff01Icon as strokeStandardNotificationOff,
  PaintBoardIcon as strokeStandardPalette,
  ClipboardPasteIcon as strokeStandardPaste,
  SmartPhone01Icon as strokeStandardPhone,
  Invoice01Icon as strokeStandardReceipt,
  RefreshIcon as strokeStandardRefresh,
  ReturnRequestIcon as strokeStandardRefund,
  Rocket01Icon as strokeStandardRocket,
  ScanIcon as strokeStandardScan,
  Search01Icon as strokeStandardSearch,
  Settings02Icon as strokeStandardSettings,
  SidebarLeftIcon as strokeStandardSidebar,
  SparklesIcon as strokeStandardSparkle,
  StarIcon as strokeStandardStar,
  Tag01Icon as strokeStandardTag,
  Target02Icon as strokeStandardTarget,
  Task01Icon as strokeStandardTask,
  ComputerTerminal01Icon as strokeStandardTerminal,
  ThumbsDownIcon as strokeStandardThumbDown,
  ThumbsUpIcon as strokeStandardThumbUp,
  UnfoldMoreIcon as strokeStandardUnfold,
  Upload01Icon as strokeStandardUpload,
  UserIcon as strokeStandardUser,
  UserGroupIcon as strokeStandardUsers,
  Alert02Icon as strokeStandardWarning,
  HierarchyCircle01Icon as strokeStandardWorkflow,
} from "@hugeicons-pro/core-stroke-standard";
import {
  Add01Icon as twotoneRoundedAdd,
  Archive02Icon as twotoneRoundedArchive,
  ArrowUp01Icon as twotoneRoundedArrowUp,
  Attachment01Icon as twotoneRoundedAttach,
  BookOpen01Icon as twotoneRoundedBook,
  BotIcon as twotoneRoundedBot,
  PackageIcon as twotoneRoundedBox,
  Calendar03Icon as twotoneRoundedCalendar,
  CreditCardIcon as twotoneRoundedCard,
  ShoppingBag01Icon as twotoneRoundedCart,
  ChartColumnIcon as twotoneRoundedChart,
  CheckmarkCircle02Icon as twotoneRoundedCheck,
  Tick02Icon as twotoneRoundedCheckmark,
  ArrowDown01Icon as twotoneRoundedChevronDown,
  Cancel01Icon as twotoneRoundedClose,
  SourceCodeIcon as twotoneRoundedCode,
  Copy01Icon as twotoneRoundedCopy,
  Scissor01Icon as twotoneRoundedCut,
  Delete02Icon as twotoneRoundedDelete,
  PencilEdit02Icon as twotoneRoundedEdit,
  LinkSquare02Icon as twotoneRoundedExternalLink,
  File01Icon as twotoneRoundedFile,
  FolderAddIcon as twotoneRoundedFolderAdd,
  FolderOpenIcon as twotoneRoundedFolderOpen,
  Globe02Icon as twotoneRoundedGlobe,
  GridViewIcon as twotoneRoundedGrid,
  HelpCircleIcon as twotoneRoundedHelp,
  Home01Icon as twotoneRoundedHome,
  LibraryIcon as twotoneRoundedLibrary,
  ListViewIcon as twotoneRoundedList,
  SquareLock02Icon as twotoneRoundedLock,
  Logout03Icon as twotoneRoundedLogout,
  Mail01Icon as twotoneRoundedMail,
  BubbleChatIcon as twotoneRoundedMessage,
  MoreHorizontalIcon as twotoneRoundedMore,
  MoreVerticalIcon as twotoneRoundedMoreVertical,
  Notification03Icon as twotoneRoundedNotification,
  NotificationOff01Icon as twotoneRoundedNotificationOff,
  PaintBoardIcon as twotoneRoundedPalette,
  ClipboardPasteIcon as twotoneRoundedPaste,
  SmartPhone01Icon as twotoneRoundedPhone,
  Invoice01Icon as twotoneRoundedReceipt,
  RefreshIcon as twotoneRoundedRefresh,
  ReturnRequestIcon as twotoneRoundedRefund,
  Rocket01Icon as twotoneRoundedRocket,
  ScanIcon as twotoneRoundedScan,
  Search01Icon as twotoneRoundedSearch,
  Settings02Icon as twotoneRoundedSettings,
  SidebarLeftIcon as twotoneRoundedSidebar,
  SparklesIcon as twotoneRoundedSparkle,
  StarIcon as twotoneRoundedStar,
  Tag01Icon as twotoneRoundedTag,
  Target02Icon as twotoneRoundedTarget,
  Task01Icon as twotoneRoundedTask,
  ComputerTerminal01Icon as twotoneRoundedTerminal,
  ThumbsDownIcon as twotoneRoundedThumbDown,
  ThumbsUpIcon as twotoneRoundedThumbUp,
  UnfoldMoreIcon as twotoneRoundedUnfold,
  Upload01Icon as twotoneRoundedUpload,
  UserIcon as twotoneRoundedUser,
  UserGroupIcon as twotoneRoundedUsers,
  Alert02Icon as twotoneRoundedWarning,
  HierarchyCircle01Icon as twotoneRoundedWorkflow,
} from "@hugeicons-pro/core-twotone-rounded";
import {
  Archive,
  ArrowUp,
  Bell,
  BellOff,
  BookOpen,
  Bot,
  Calendar,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronsUpDown,
  CircleCheck,
  CircleQuestionMark,
  ClipboardPaste,
  CodeXml,
  Copy,
  CreditCard,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  FileText,
  FolderOpen,
  FolderPlus,
  Globe,
  House,
  LayoutGrid,
  Library,
  ListChecks,
  Lock,
  LogOut,
  type LucideIcon,
  Mail,
  MessageCircle,
  Package,
  Palette,
  PanelLeft,
  Paperclip,
  Plus,
  Receipt,
  RefreshCw,
  Rocket,
  RotateCcw,
  Scan,
  Scissors,
  Search,
  Settings,
  ShoppingBag,
  Smartphone,
  Sparkles,
  SquareCheck,
  SquarePen,
  SquareTerminal,
  Star,
  Tag,
  Target,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  Users,
  Waypoints,
  X,
} from "lucide-react";
import { type ComponentProps, createElement, type ReactElement } from "react";

type IconSettings = DesignSystem["icons"];
type HugeiconsSettings = Extract<IconSettings, { family: "hugeicons" }>;
type IconData = ComponentProps<typeof HugeiconsIcon>["icon"];

export type PreviewIconName =
  | "add"
  | "archive"
  | "arrowUp"
  | "attach"
  | "book"
  | "bot"
  | "box"
  | "calendar"
  | "card"
  | "cart"
  | "chart"
  | "check"
  | "checkmark"
  | "chevronDown"
  | "close"
  | "code"
  | "copy"
  | "cut"
  | "delete"
  | "edit"
  | "externalLink"
  | "file"
  | "folderAdd"
  | "folderOpen"
  | "globe"
  | "grid"
  | "help"
  | "home"
  | "library"
  | "list"
  | "lock"
  | "logout"
  | "mail"
  | "message"
  | "more"
  | "moreVertical"
  | "notification"
  | "notificationOff"
  | "palette"
  | "paste"
  | "phone"
  | "receipt"
  | "refresh"
  | "refund"
  | "rocket"
  | "scan"
  | "search"
  | "settings"
  | "sidebar"
  | "sparkle"
  | "star"
  | "tag"
  | "target"
  | "task"
  | "terminal"
  | "thumbDown"
  | "thumbUp"
  | "unfold"
  | "upload"
  | "user"
  | "users"
  | "warning"
  | "workflow";

export type PreviewIconElements = Record<PreviewIconName, ReactElement>;

const previewIconNames: PreviewIconName[] = [
  "add",
  "archive",
  "arrowUp",
  "attach",
  "book",
  "bot",
  "box",
  "calendar",
  "card",
  "cart",
  "chart",
  "check",
  "checkmark",
  "chevronDown",
  "close",
  "code",
  "copy",
  "cut",
  "delete",
  "edit",
  "externalLink",
  "file",
  "folderAdd",
  "folderOpen",
  "globe",
  "grid",
  "help",
  "home",
  "library",
  "list",
  "lock",
  "logout",
  "mail",
  "message",
  "more",
  "moreVertical",
  "notification",
  "notificationOff",
  "palette",
  "paste",
  "phone",
  "receipt",
  "refresh",
  "refund",
  "rocket",
  "scan",
  "search",
  "settings",
  "sidebar",
  "sparkle",
  "star",
  "tag",
  "target",
  "task",
  "terminal",
  "thumbDown",
  "thumbUp",
  "unfold",
  "upload",
  "user",
  "users",
  "warning",
  "workflow",
];

const lucideIcons = {
  add: Plus,
  archive: Archive,
  arrowUp: ArrowUp,
  attach: Paperclip,
  book: BookOpen,
  bot: Bot,
  box: Package,
  calendar: Calendar,
  card: CreditCard,
  cart: ShoppingBag,
  chart: ChartColumn,
  check: CircleCheck,
  checkmark: Check,
  chevronDown: ChevronDown,
  close: X,
  code: CodeXml,
  copy: Copy,
  cut: Scissors,
  delete: Trash2,
  edit: SquarePen,
  externalLink: ExternalLink,
  file: FileText,
  folderAdd: FolderPlus,
  folderOpen: FolderOpen,
  globe: Globe,
  grid: LayoutGrid,
  help: CircleQuestionMark,
  home: House,
  library: Library,
  list: ListChecks,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  message: MessageCircle,
  more: Ellipsis,
  moreVertical: EllipsisVertical,
  notification: Bell,
  notificationOff: BellOff,
  palette: Palette,
  paste: ClipboardPaste,
  phone: Smartphone,
  receipt: Receipt,
  refresh: RefreshCw,
  refund: RotateCcw,
  rocket: Rocket,
  scan: Scan,
  search: Search,
  settings: Settings,
  sidebar: PanelLeft,
  sparkle: Sparkles,
  star: Star,
  tag: Tag,
  target: Target,
  task: SquareCheck,
  terminal: SquareTerminal,
  thumbDown: ThumbsDown,
  thumbUp: ThumbsUp,
  unfold: ChevronsUpDown,
  upload: Upload,
  user: User,
  users: Users,
  warning: TriangleAlert,
  workflow: Waypoints,
} satisfies Record<PreviewIconName, LucideIcon>;

// Keep package specifiers static so Vite can tree-shake each treatment to this preview vocabulary.
const hugeiconsByTreatment = {
  "bulk-rounded": hugeicons(
    bulkRoundedAdd,
    bulkRoundedArchive,
    bulkRoundedArrowUp,
    bulkRoundedAttach,
    bulkRoundedBook,
    bulkRoundedBot,
    bulkRoundedBox,
    bulkRoundedCalendar,
    bulkRoundedCard,
    bulkRoundedCart,
    bulkRoundedChart,
    bulkRoundedCheck,
    bulkRoundedCheckmark,
    bulkRoundedChevronDown,
    bulkRoundedClose,
    bulkRoundedCode,
    bulkRoundedCopy,
    bulkRoundedCut,
    bulkRoundedDelete,
    bulkRoundedEdit,
    bulkRoundedExternalLink,
    bulkRoundedFile,
    bulkRoundedFolderAdd,
    bulkRoundedFolderOpen,
    bulkRoundedGlobe,
    bulkRoundedGrid,
    bulkRoundedHelp,
    bulkRoundedHome,
    bulkRoundedLibrary,
    bulkRoundedList,
    bulkRoundedLock,
    bulkRoundedLogout,
    bulkRoundedMail,
    bulkRoundedMessage,
    bulkRoundedMore,
    bulkRoundedMoreVertical,
    bulkRoundedNotification,
    bulkRoundedNotificationOff,
    bulkRoundedPalette,
    bulkRoundedPaste,
    bulkRoundedPhone,
    bulkRoundedReceipt,
    bulkRoundedRefresh,
    bulkRoundedRefund,
    bulkRoundedRocket,
    bulkRoundedScan,
    bulkRoundedSearch,
    bulkRoundedSettings,
    bulkRoundedSidebar,
    bulkRoundedSparkle,
    bulkRoundedStar,
    bulkRoundedTag,
    bulkRoundedTarget,
    bulkRoundedTask,
    bulkRoundedTerminal,
    bulkRoundedThumbDown,
    bulkRoundedThumbUp,
    bulkRoundedUnfold,
    bulkRoundedUpload,
    bulkRoundedUser,
    bulkRoundedUsers,
    bulkRoundedWarning,
    bulkRoundedWorkflow,
  ),
  "duotone-rounded": hugeicons(
    duotoneRoundedAdd,
    duotoneRoundedArchive,
    duotoneRoundedArrowUp,
    duotoneRoundedAttach,
    duotoneRoundedBook,
    duotoneRoundedBot,
    duotoneRoundedBox,
    duotoneRoundedCalendar,
    duotoneRoundedCard,
    duotoneRoundedCart,
    duotoneRoundedChart,
    duotoneRoundedCheck,
    duotoneRoundedCheckmark,
    duotoneRoundedChevronDown,
    duotoneRoundedClose,
    duotoneRoundedCode,
    duotoneRoundedCopy,
    duotoneRoundedCut,
    duotoneRoundedDelete,
    duotoneRoundedEdit,
    duotoneRoundedExternalLink,
    duotoneRoundedFile,
    duotoneRoundedFolderAdd,
    duotoneRoundedFolderOpen,
    duotoneRoundedGlobe,
    duotoneRoundedGrid,
    duotoneRoundedHelp,
    duotoneRoundedHome,
    duotoneRoundedLibrary,
    duotoneRoundedList,
    duotoneRoundedLock,
    duotoneRoundedLogout,
    duotoneRoundedMail,
    duotoneRoundedMessage,
    duotoneRoundedMore,
    duotoneRoundedMoreVertical,
    duotoneRoundedNotification,
    duotoneRoundedNotificationOff,
    duotoneRoundedPalette,
    duotoneRoundedPaste,
    duotoneRoundedPhone,
    duotoneRoundedReceipt,
    duotoneRoundedRefresh,
    duotoneRoundedRefund,
    duotoneRoundedRocket,
    duotoneRoundedScan,
    duotoneRoundedSearch,
    duotoneRoundedSettings,
    duotoneRoundedSidebar,
    duotoneRoundedSparkle,
    duotoneRoundedStar,
    duotoneRoundedTag,
    duotoneRoundedTarget,
    duotoneRoundedTask,
    duotoneRoundedTerminal,
    duotoneRoundedThumbDown,
    duotoneRoundedThumbUp,
    duotoneRoundedUnfold,
    duotoneRoundedUpload,
    duotoneRoundedUser,
    duotoneRoundedUsers,
    duotoneRoundedWarning,
    duotoneRoundedWorkflow,
  ),
  "duotone-standard": hugeicons(
    duotoneStandardAdd,
    duotoneStandardArchive,
    duotoneStandardArrowUp,
    duotoneStandardAttach,
    duotoneStandardBook,
    duotoneStandardBot,
    duotoneStandardBox,
    duotoneStandardCalendar,
    duotoneStandardCard,
    duotoneStandardCart,
    duotoneStandardChart,
    duotoneStandardCheck,
    duotoneStandardCheckmark,
    duotoneStandardChevronDown,
    duotoneStandardClose,
    duotoneStandardCode,
    duotoneStandardCopy,
    duotoneStandardCut,
    duotoneStandardDelete,
    duotoneStandardEdit,
    duotoneStandardExternalLink,
    duotoneStandardFile,
    duotoneStandardFolderAdd,
    duotoneStandardFolderOpen,
    duotoneStandardGlobe,
    duotoneStandardGrid,
    duotoneStandardHelp,
    duotoneStandardHome,
    duotoneStandardLibrary,
    duotoneStandardList,
    duotoneStandardLock,
    duotoneStandardLogout,
    duotoneStandardMail,
    duotoneStandardMessage,
    duotoneStandardMore,
    duotoneStandardMoreVertical,
    duotoneStandardNotification,
    duotoneStandardNotificationOff,
    duotoneStandardPalette,
    duotoneStandardPaste,
    duotoneStandardPhone,
    duotoneStandardReceipt,
    duotoneStandardRefresh,
    duotoneStandardRefund,
    duotoneStandardRocket,
    duotoneStandardScan,
    duotoneStandardSearch,
    duotoneStandardSettings,
    duotoneStandardSidebar,
    duotoneStandardSparkle,
    duotoneStandardStar,
    duotoneStandardTag,
    duotoneStandardTarget,
    duotoneStandardTask,
    duotoneStandardTerminal,
    duotoneStandardThumbDown,
    duotoneStandardThumbUp,
    duotoneStandardUnfold,
    duotoneStandardUpload,
    duotoneStandardUser,
    duotoneStandardUsers,
    duotoneStandardWarning,
    duotoneStandardWorkflow,
  ),
  "solid-rounded": hugeicons(
    solidRoundedAdd,
    solidRoundedArchive,
    solidRoundedArrowUp,
    solidRoundedAttach,
    solidRoundedBook,
    solidRoundedBot,
    solidRoundedBox,
    solidRoundedCalendar,
    solidRoundedCard,
    solidRoundedCart,
    solidRoundedChart,
    solidRoundedCheck,
    solidRoundedCheckmark,
    solidRoundedChevronDown,
    solidRoundedClose,
    solidRoundedCode,
    solidRoundedCopy,
    solidRoundedCut,
    solidRoundedDelete,
    solidRoundedEdit,
    solidRoundedExternalLink,
    solidRoundedFile,
    solidRoundedFolderAdd,
    solidRoundedFolderOpen,
    solidRoundedGlobe,
    solidRoundedGrid,
    solidRoundedHelp,
    solidRoundedHome,
    solidRoundedLibrary,
    solidRoundedList,
    solidRoundedLock,
    solidRoundedLogout,
    solidRoundedMail,
    solidRoundedMessage,
    solidRoundedMore,
    solidRoundedMoreVertical,
    solidRoundedNotification,
    solidRoundedNotificationOff,
    solidRoundedPalette,
    solidRoundedPaste,
    solidRoundedPhone,
    solidRoundedReceipt,
    solidRoundedRefresh,
    solidRoundedRefund,
    solidRoundedRocket,
    solidRoundedScan,
    solidRoundedSearch,
    solidRoundedSettings,
    solidRoundedSidebar,
    solidRoundedSparkle,
    solidRoundedStar,
    solidRoundedTag,
    solidRoundedTarget,
    solidRoundedTask,
    solidRoundedTerminal,
    solidRoundedThumbDown,
    solidRoundedThumbUp,
    solidRoundedUnfold,
    solidRoundedUpload,
    solidRoundedUser,
    solidRoundedUsers,
    solidRoundedWarning,
    solidRoundedWorkflow,
  ),
  "solid-sharp": hugeicons(
    solidSharpAdd,
    solidSharpArchive,
    solidSharpArrowUp,
    solidSharpAttach,
    solidSharpBook,
    solidSharpBot,
    solidSharpBox,
    solidSharpCalendar,
    solidSharpCard,
    solidSharpCart,
    solidSharpChart,
    solidSharpCheck,
    solidSharpCheckmark,
    solidSharpChevronDown,
    solidSharpClose,
    solidSharpCode,
    solidSharpCopy,
    solidSharpCut,
    solidSharpDelete,
    solidSharpEdit,
    solidSharpExternalLink,
    solidSharpFile,
    solidSharpFolderAdd,
    solidSharpFolderOpen,
    solidSharpGlobe,
    solidSharpGrid,
    solidSharpHelp,
    solidSharpHome,
    solidSharpLibrary,
    solidSharpList,
    solidSharpLock,
    solidSharpLogout,
    solidSharpMail,
    solidSharpMessage,
    solidSharpMore,
    solidSharpMoreVertical,
    solidSharpNotification,
    solidSharpNotificationOff,
    solidSharpPalette,
    solidSharpPaste,
    solidSharpPhone,
    solidSharpReceipt,
    solidSharpRefresh,
    solidSharpRefund,
    solidSharpRocket,
    solidSharpScan,
    solidSharpSearch,
    solidSharpSettings,
    solidSharpSidebar,
    solidSharpSparkle,
    solidSharpStar,
    solidSharpTag,
    solidSharpTarget,
    solidSharpTask,
    solidSharpTerminal,
    solidSharpThumbDown,
    solidSharpThumbUp,
    solidSharpUnfold,
    solidSharpUpload,
    solidSharpUser,
    solidSharpUsers,
    solidSharpWarning,
    solidSharpWorkflow,
  ),
  "solid-standard": hugeicons(
    solidStandardAdd,
    solidStandardArchive,
    solidStandardArrowUp,
    solidStandardAttach,
    solidStandardBook,
    solidStandardBot,
    solidStandardBox,
    solidStandardCalendar,
    solidStandardCard,
    solidStandardCart,
    solidStandardChart,
    solidStandardCheck,
    solidStandardCheckmark,
    solidStandardChevronDown,
    solidStandardClose,
    solidStandardCode,
    solidStandardCopy,
    solidStandardCut,
    solidStandardDelete,
    solidStandardEdit,
    solidStandardExternalLink,
    solidStandardFile,
    solidStandardFolderAdd,
    solidStandardFolderOpen,
    solidStandardGlobe,
    solidStandardGrid,
    solidStandardHelp,
    solidStandardHome,
    solidStandardLibrary,
    solidStandardList,
    solidStandardLock,
    solidStandardLogout,
    solidStandardMail,
    solidStandardMessage,
    solidStandardMore,
    solidStandardMoreVertical,
    solidStandardNotification,
    solidStandardNotificationOff,
    solidStandardPalette,
    solidStandardPaste,
    solidStandardPhone,
    solidStandardReceipt,
    solidStandardRefresh,
    solidStandardRefund,
    solidStandardRocket,
    solidStandardScan,
    solidStandardSearch,
    solidStandardSettings,
    solidStandardSidebar,
    solidStandardSparkle,
    solidStandardStar,
    solidStandardTag,
    solidStandardTarget,
    solidStandardTask,
    solidStandardTerminal,
    solidStandardThumbDown,
    solidStandardThumbUp,
    solidStandardUnfold,
    solidStandardUpload,
    solidStandardUser,
    solidStandardUsers,
    solidStandardWarning,
    solidStandardWorkflow,
  ),
  "stroke-rounded": hugeicons(
    strokeRoundedAdd,
    strokeRoundedArchive,
    strokeRoundedArrowUp,
    strokeRoundedAttach,
    strokeRoundedBook,
    strokeRoundedBot,
    strokeRoundedBox,
    strokeRoundedCalendar,
    strokeRoundedCard,
    strokeRoundedCart,
    strokeRoundedChart,
    strokeRoundedCheck,
    strokeRoundedCheckmark,
    strokeRoundedChevronDown,
    strokeRoundedClose,
    strokeRoundedCode,
    strokeRoundedCopy,
    strokeRoundedCut,
    strokeRoundedDelete,
    strokeRoundedEdit,
    strokeRoundedExternalLink,
    strokeRoundedFile,
    strokeRoundedFolderAdd,
    strokeRoundedFolderOpen,
    strokeRoundedGlobe,
    strokeRoundedGrid,
    strokeRoundedHelp,
    strokeRoundedHome,
    strokeRoundedLibrary,
    strokeRoundedList,
    strokeRoundedLock,
    strokeRoundedLogout,
    strokeRoundedMail,
    strokeRoundedMessage,
    strokeRoundedMore,
    strokeRoundedMoreVertical,
    strokeRoundedNotification,
    strokeRoundedNotificationOff,
    strokeRoundedPalette,
    strokeRoundedPaste,
    strokeRoundedPhone,
    strokeRoundedReceipt,
    strokeRoundedRefresh,
    strokeRoundedRefund,
    strokeRoundedRocket,
    strokeRoundedScan,
    strokeRoundedSearch,
    strokeRoundedSettings,
    strokeRoundedSidebar,
    strokeRoundedSparkle,
    strokeRoundedStar,
    strokeRoundedTag,
    strokeRoundedTarget,
    strokeRoundedTask,
    strokeRoundedTerminal,
    strokeRoundedThumbDown,
    strokeRoundedThumbUp,
    strokeRoundedUnfold,
    strokeRoundedUpload,
    strokeRoundedUser,
    strokeRoundedUsers,
    strokeRoundedWarning,
    strokeRoundedWorkflow,
  ),
  "stroke-sharp": hugeicons(
    strokeSharpAdd,
    strokeSharpArchive,
    strokeSharpArrowUp,
    strokeSharpAttach,
    strokeSharpBook,
    strokeSharpBot,
    strokeSharpBox,
    strokeSharpCalendar,
    strokeSharpCard,
    strokeSharpCart,
    strokeSharpChart,
    strokeSharpCheck,
    strokeSharpCheckmark,
    strokeSharpChevronDown,
    strokeSharpClose,
    strokeSharpCode,
    strokeSharpCopy,
    strokeSharpCut,
    strokeSharpDelete,
    strokeSharpEdit,
    strokeSharpExternalLink,
    strokeSharpFile,
    strokeSharpFolderAdd,
    strokeSharpFolderOpen,
    strokeSharpGlobe,
    strokeSharpGrid,
    strokeSharpHelp,
    strokeSharpHome,
    strokeSharpLibrary,
    strokeSharpList,
    strokeSharpLock,
    strokeSharpLogout,
    strokeSharpMail,
    strokeSharpMessage,
    strokeSharpMore,
    strokeSharpMoreVertical,
    strokeSharpNotification,
    strokeSharpNotificationOff,
    strokeSharpPalette,
    strokeSharpPaste,
    strokeSharpPhone,
    strokeSharpReceipt,
    strokeSharpRefresh,
    strokeSharpRefund,
    strokeSharpRocket,
    strokeSharpScan,
    strokeSharpSearch,
    strokeSharpSettings,
    strokeSharpSidebar,
    strokeSharpSparkle,
    strokeSharpStar,
    strokeSharpTag,
    strokeSharpTarget,
    strokeSharpTask,
    strokeSharpTerminal,
    strokeSharpThumbDown,
    strokeSharpThumbUp,
    strokeSharpUnfold,
    strokeSharpUpload,
    strokeSharpUser,
    strokeSharpUsers,
    strokeSharpWarning,
    strokeSharpWorkflow,
  ),
  "stroke-standard": hugeicons(
    strokeStandardAdd,
    strokeStandardArchive,
    strokeStandardArrowUp,
    strokeStandardAttach,
    strokeStandardBook,
    strokeStandardBot,
    strokeStandardBox,
    strokeStandardCalendar,
    strokeStandardCard,
    strokeStandardCart,
    strokeStandardChart,
    strokeStandardCheck,
    strokeStandardCheckmark,
    strokeStandardChevronDown,
    strokeStandardClose,
    strokeStandardCode,
    strokeStandardCopy,
    strokeStandardCut,
    strokeStandardDelete,
    strokeStandardEdit,
    strokeStandardExternalLink,
    strokeStandardFile,
    strokeStandardFolderAdd,
    strokeStandardFolderOpen,
    strokeStandardGlobe,
    strokeStandardGrid,
    strokeStandardHelp,
    strokeStandardHome,
    strokeStandardLibrary,
    strokeStandardList,
    strokeStandardLock,
    strokeStandardLogout,
    strokeStandardMail,
    strokeStandardMessage,
    strokeStandardMore,
    strokeStandardMoreVertical,
    strokeStandardNotification,
    strokeStandardNotificationOff,
    strokeStandardPalette,
    strokeStandardPaste,
    strokeStandardPhone,
    strokeStandardReceipt,
    strokeStandardRefresh,
    strokeStandardRefund,
    strokeStandardRocket,
    strokeStandardScan,
    strokeStandardSearch,
    strokeStandardSettings,
    strokeStandardSidebar,
    strokeStandardSparkle,
    strokeStandardStar,
    strokeStandardTag,
    strokeStandardTarget,
    strokeStandardTask,
    strokeStandardTerminal,
    strokeStandardThumbDown,
    strokeStandardThumbUp,
    strokeStandardUnfold,
    strokeStandardUpload,
    strokeStandardUser,
    strokeStandardUsers,
    strokeStandardWarning,
    strokeStandardWorkflow,
  ),
  "twotone-rounded": hugeicons(
    twotoneRoundedAdd,
    twotoneRoundedArchive,
    twotoneRoundedArrowUp,
    twotoneRoundedAttach,
    twotoneRoundedBook,
    twotoneRoundedBot,
    twotoneRoundedBox,
    twotoneRoundedCalendar,
    twotoneRoundedCard,
    twotoneRoundedCart,
    twotoneRoundedChart,
    twotoneRoundedCheck,
    twotoneRoundedCheckmark,
    twotoneRoundedChevronDown,
    twotoneRoundedClose,
    twotoneRoundedCode,
    twotoneRoundedCopy,
    twotoneRoundedCut,
    twotoneRoundedDelete,
    twotoneRoundedEdit,
    twotoneRoundedExternalLink,
    twotoneRoundedFile,
    twotoneRoundedFolderAdd,
    twotoneRoundedFolderOpen,
    twotoneRoundedGlobe,
    twotoneRoundedGrid,
    twotoneRoundedHelp,
    twotoneRoundedHome,
    twotoneRoundedLibrary,
    twotoneRoundedList,
    twotoneRoundedLock,
    twotoneRoundedLogout,
    twotoneRoundedMail,
    twotoneRoundedMessage,
    twotoneRoundedMore,
    twotoneRoundedMoreVertical,
    twotoneRoundedNotification,
    twotoneRoundedNotificationOff,
    twotoneRoundedPalette,
    twotoneRoundedPaste,
    twotoneRoundedPhone,
    twotoneRoundedReceipt,
    twotoneRoundedRefresh,
    twotoneRoundedRefund,
    twotoneRoundedRocket,
    twotoneRoundedScan,
    twotoneRoundedSearch,
    twotoneRoundedSettings,
    twotoneRoundedSidebar,
    twotoneRoundedSparkle,
    twotoneRoundedStar,
    twotoneRoundedTag,
    twotoneRoundedTarget,
    twotoneRoundedTask,
    twotoneRoundedTerminal,
    twotoneRoundedThumbDown,
    twotoneRoundedThumbUp,
    twotoneRoundedUnfold,
    twotoneRoundedUpload,
    twotoneRoundedUser,
    twotoneRoundedUsers,
    twotoneRoundedWarning,
    twotoneRoundedWorkflow,
  ),
} satisfies Record<HugeiconsSettings["treatment"], Record<PreviewIconName, IconData>>;

export function createPreviewIconElements(settings: IconSettings): PreviewIconElements {
  return Object.fromEntries(
    previewIconNames.map((name) => [name, previewIconElement(name, settings)]),
  ) as PreviewIconElements;
}

function previewIconElement(name: PreviewIconName, settings: IconSettings): ReactElement {
  if (settings.family === "lucide") {
    return createElement(lucideIcons[name], {
      "aria-hidden": true,
      className: "preview-icon",
      size: settings.size,
      strokeWidth: settings.strokeWidth,
    });
  }

  return createElement(HugeiconsIcon, {
    "aria-hidden": true,
    className: "preview-icon",
    icon: hugeiconsByTreatment[settings.treatment][name],
    size: settings.size,
    strokeWidth: settings.strokeWidth,
  });
}

function hugeicons(
  add: IconData,
  archive: IconData,
  arrowUp: IconData,
  attach: IconData,
  book: IconData,
  bot: IconData,
  box: IconData,
  calendar: IconData,
  card: IconData,
  cart: IconData,
  chart: IconData,
  check: IconData,
  checkmark: IconData,
  chevronDown: IconData,
  close: IconData,
  code: IconData,
  copy: IconData,
  cut: IconData,
  deleteIcon: IconData,
  edit: IconData,
  externalLink: IconData,
  file: IconData,
  folderAdd: IconData,
  folderOpen: IconData,
  globe: IconData,
  grid: IconData,
  help: IconData,
  home: IconData,
  library: IconData,
  list: IconData,
  lock: IconData,
  logout: IconData,
  mail: IconData,
  message: IconData,
  more: IconData,
  moreVertical: IconData,
  notification: IconData,
  notificationOff: IconData,
  palette: IconData,
  paste: IconData,
  phone: IconData,
  receipt: IconData,
  refresh: IconData,
  refund: IconData,
  rocket: IconData,
  scan: IconData,
  search: IconData,
  settings: IconData,
  sidebar: IconData,
  sparkle: IconData,
  star: IconData,
  tag: IconData,
  target: IconData,
  task: IconData,
  terminal: IconData,
  thumbDown: IconData,
  thumbUp: IconData,
  unfold: IconData,
  upload: IconData,
  user: IconData,
  users: IconData,
  warning: IconData,
  workflow: IconData,
): Record<PreviewIconName, IconData> {
  return {
    add,
    archive,
    arrowUp,
    attach,
    book,
    bot,
    box,
    calendar,
    card,
    cart,
    chart,
    check,
    checkmark,
    chevronDown,
    close,
    code,
    copy,
    cut,
    delete: deleteIcon,
    edit,
    externalLink,
    file,
    folderAdd,
    folderOpen,
    globe,
    grid,
    help,
    home,
    library,
    list,
    lock,
    logout,
    mail,
    message,
    more,
    moreVertical,
    notification,
    notificationOff,
    palette,
    paste,
    phone,
    receipt,
    refresh,
    refund,
    rocket,
    scan,
    search,
    settings,
    sidebar,
    sparkle,
    star,
    tag,
    target,
    task,
    terminal,
    thumbDown,
    thumbUp,
    unfold,
    upload,
    user,
    users,
    warning,
    workflow,
  };
}
