/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SchemaDotjsonRouteImport } from './routes/schema[.]json'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as DsIdRouteImport } from './routes/ds.$id'
import { Route as DsIdIndexRouteImport } from './routes/ds.$id.index'
import { Route as DsIdSectionRouteImport } from './routes/ds.$id.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaDotjsonRoute = SchemaDotjsonRouteImport.update({
  id: '/schema.json',
  path: '/schema.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const DsIdRoute = DsIdRouteImport.update({
  id: '/ds/$id',
  path: '/ds/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DsIdIndexRoute = DsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DsIdRoute,
} as any)
const DsIdSectionRoute = DsIdSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => DsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/schema.json': typeof SchemaDotjsonRoute
  '/systems': typeof SystemsRoute
  '/ds/$id': typeof DsIdRouteWithChildren
  '/ds/$id/$section': typeof DsIdSectionRoute
  '/ds/$id/': typeof DsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/schema.json': typeof SchemaDotjsonRoute
  '/systems': typeof SystemsRoute
  '/ds/$id/$section': typeof DsIdSectionRoute
  '/ds/$id': typeof DsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/schema.json': typeof SchemaDotjsonRoute
  '/systems': typeof SystemsRoute
  '/ds/$id': typeof DsIdRouteWithChildren
  '/ds/$id/$section': typeof DsIdSectionRoute
  '/ds/$id/': typeof DsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/schema.json'
    | '/systems'
    | '/ds/$id'
    | '/ds/$id/$section'
    | '/ds/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/schema.json'
    | '/systems'
    | '/ds/$id/$section'
    | '/ds/$id'
  id:
    | '__root__'
    | '/'
    | '/pricing'
    | '/schema.json'
    | '/systems'
    | '/ds/$id'
    | '/ds/$id/$section'
    | '/ds/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  SchemaDotjsonRoute: typeof SchemaDotjsonRoute
  SystemsRoute: typeof SystemsRoute
  DsIdRoute: typeof DsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema.json': {
      id: '/schema.json'
      path: '/schema.json'
      fullPath: '/schema.json'
      preLoaderRoute: typeof SchemaDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/$id': {
      id: '/ds/$id'
      path: '/ds/$id'
      fullPath: '/ds/$id'
      preLoaderRoute: typeof DsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/$id/': {
      id: '/ds/$id/'
      path: '/'
      fullPath: '/ds/$id/'
      preLoaderRoute: typeof DsIdIndexRouteImport
      parentRoute: typeof DsIdRoute
    }
    '/ds/$id/$section': {
      id: '/ds/$id/$section'
      path: '/$section'
      fullPath: '/ds/$id/$section'
      preLoaderRoute: typeof DsIdSectionRouteImport
      parentRoute: typeof DsIdRoute
    }
  }
}

interface DsIdRouteChildren {
  DsIdSectionRoute: typeof DsIdSectionRoute
  DsIdIndexRoute: typeof DsIdIndexRoute
}

const DsIdRouteChildren: DsIdRouteChildren = {
  DsIdSectionRoute: DsIdSectionRoute,
  DsIdIndexRoute: DsIdIndexRoute,
}

const DsIdRouteWithChildren = DsIdRoute._addFileChildren(DsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  SchemaDotjsonRoute: SchemaDotjsonRoute,
  SystemsRoute: SystemsRoute,
  DsIdRoute: DsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
